---
title: "HW3"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{HW3}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# I used Chatgpt for brainstorming the algorithm and code for compute_maximal_partial_clique. I came up with a few ideas but ultimately failed on correctness/efficiency. It is a hard problem that I find it very challenging to come up with efficient and correct solution. I think the chatgpt one provide an efficient solution enough for this HW purpose although not ensuring 100% accuracy. 
library(UWBiost561)
set.seed(0)
simulation <- UWBiost561::generate_partial_clique(
  n = 10,
  clique_fraction = 0.5,
  clique_edge_density = 0.9
)

adj_mat <- simulation$adj_mat

res <- UWBiost561::compute_maximal_partial_clique(
  adj_mat = adj_mat,
  alpha = 0.9
)
res
```

```{r}
devtools::session_info()

```


## 5b

I dont have a prior project in mind, All of my computer science project are in python/java and I think it can be time consuming to convert to R. I'll try to go through the past projects and see what I can use. 

